
services:
  mongodb:
    image: mongo:latest
    container_name: gooinprochatdb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # 관리자 사용자 이름
      MONGO_INITDB_ROOT_PASSWORD: ROOT  # 관리자 비밀번호
      MONGO_INITDB_DATABASE: gooinprochatdb          # 기본 데이터베이스 이름
    volumes:
      - ./init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js  # 초기화 스크립트를 컨테이너로 마운트

  gooinpro_chat_api_container:
    image: hyeong123/gooinpro_chat_api_container
    container_name: gooinpro_chat_api
    restart: always
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://gooinprochatdbuser:gooinprochatdbuser@gooinprochatdb:27017/gooinprochatdb?authSource=gooinprochatdb"
    ports:
      - "8088:8080"
