spring:
  application:
    name: GooInProChatAPI

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://gooinprochatdbuser:gooinprochatdbuser@gooinprochatdb:27017/gooinprochatdb?authSource=gooinprochatdb}

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false